### ISSUE TITLE
TextField crashes when its inside of Popup

### ISSUE THREAD

**Issue by AleksSamaniego** [yiszza/Material.Components.Maui#10]
### Discussed in https://github.com/mdc-maui/mdc-maui/discussions/9

<div type='discussions-op-text'>

<sup>Originally posted by **AleksSamaniego** March 30, 2023</sup>
When you insert a TextField into a Popup, and then you click on the TextField, it crashes.
![image](https://user-images.githubusercontent.com/11296760/228908320-1333fe3d-b39e-4d08-b74f-fb97d49d06be.png)

![image](https://user-images.githubusercontent.com/11296760/228908446-a46dd20c-5066-4e4e-aa93-46fdb9c2102b.png)
</div>

**Comment by yiszza** [comment]
Copy!

**Comment by yiszza** [comment]
Fixed in 158da7b

**Comment by DharunAR** [comment]
May I know when the Fixed Solution will be available in the Nuget? We are using Material controls with .NET MAUI and this text field issue is blocking us on development and also in testing. Please let me know the updates about the next version Nuget release please.

**Comment by yiszza** [comment]
> May I know when the Fixed Solution will be available in the Nuget? We are using Material controls with .NET MAUI and this text field issue is blocking us on development and also in testing. Please let me know the updates about the next version Nuget release please.

1 week.
