### ISSUE TITLE
[Microsoft.WindowsAppSDK = 1.3.230331000] TextField is not clickable/focusable

### ISSUE THREAD

**Issue by MateuszLas421** [yiszza/Material.Components.Maui#12]
Currently a low priority bug

`Exception thrown: 'SharpGen.Runtime.SharpGenException' in SharpGen.Runtime.dll
An exception of type 'SharpGen.Runtime.SharpGenException' occurred in SharpGen.Runtime.dll but was not handled in user code
HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is invalid.`

In an application, e.g. MAUI using WindowsAppSDK 1.3.XYZ, it is impossible to click on the TextField. With Standard 1.2.XYZ. works correctly.
![image](https://user-images.githubusercontent.com/36116587/232551326-1fe98b4e-8aac-423a-999a-ed9b2cb32405.png)

**Comment by yiszza** [comment]
Fixed in 158da7b
