### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by yegor-pelykh** [yiszza/Material.Components.Maui#13]
How to change theme / change colors?

**Comment by yiszza** [comment]
Use seedColor on the App.xaml.
like:
```xaml
...
 <mds:MaterialStyles Dark="DarkBlue" Light="Green" />
...
```

**Comment by yegor-pelykh** [comment]
Thanks a lot! Will the color of the ripple effect change too by going this way?

**Comment by yiszza** [comment]
Yes, Material design use seedColor to generate  a colors scheme. https://github.com/material-foundation/material-color-utilities

**Comment by yegor-pelykh** [comment]
Great! Thank you!
