### ISSUE TITLE
Context Menu and Combo box items don't appear on windows (works fine on android) 

### ISSUE THREAD

**Issue by MahmoudAlEssawi** [yiszza/Material.Components.Maui#14]
Hi thanks for this great package,

I tried to use combo box and context menu on windows (right click, left click and log press) but it shows nothing on windows.

I need your help with that 

I used the sample xaml file as follows:

    <ScrollView Padding="30,20">
        <VerticalStackLayout Spacing="15">
            <md:Label
                FontSize="18"
                HorizontalOptions="Start"
                Text="{OnIdiom Default=long press button  ↓↓↓,
                               Desktop=right click button ↓↓↓}" />

            <md:WrapLayout
                Padding="20"
                HorizontalSpacing="50"
                VerticalSpacing="15">
                <md:Button   
                    IconKind="Menu"
                    Text="button"
                    VerticalOptions="Center">
                    <md:Button.ContextMenu >
                        <md:ContextMenu  >
                            <md:MenuItem 
                                IconKind="Menu"
                                Text="item 1" />
                            <md:MenuItem  
                                IconKind="Menu"
                                Text="item 2" />
                            <md:MenuItem 
                                IconKind="Menu"
                                Text="item 3" />
                        </md:ContextMenu>
                    </md:Button.ContextMenu>
                </md:Button>
                <md:IconButton IconKind="Menu" VerticalOptions="Center">
                    <md:IconButton.ContextMenu>
                        <md:ContextMenu>
                            <md:MenuItem
                                Command="{Binding MenuItemClickedCommand}"
                                CommandParameter="{Binding Source={RelativeSource Self}, Path=Text}"
                                IconKind="Star"
                                Text="one" />
                            <md:MenuItem
                                Command="{Binding MenuItemClickedCommand}"
                                CommandParameter="{Binding Source={RelativeSource Self}, Path=Text}"
                                IconKind="Star"
                                Text="two" />
                            <md:MenuItem
                                Command="{Binding MenuItemClickedCommand}"
                                CommandParameter="{Binding Source={RelativeSource Self}, Path=Text}"
                                IconKind="Star"
                                Text="three" />
                        </md:ContextMenu>
                    </md:IconButton.ContextMenu>
                </md:IconButton>
                <md:FAB IconKind="Settings" VerticalOptions="Center">
                    <md:FAB.ContextMenu>
                        <md:ContextMenu>
                            <md:MenuItem
                                Command="{Binding MenuItemClickedCommand}"
                                CommandParameter="{Binding Source={RelativeSource Self}, Path=Text}"
                                IconKind="Park"
                                Text="item 1" />
                            <md:MenuItem
                                Command="{Binding MenuItemClickedCommand}"
                                CommandParameter="{Binding Source={RelativeSource Self}, Path=Text}"
                                IconKind="Park"
                                Text="item 2" />
                            <md:MenuItem
                                Command="{Binding MenuItemClickedCommand}"
                                CommandParameter="{Binding Source={RelativeSource Self}, Path=Text}"
                                IconKind="Park"
                                Text="item 3" />
                        </md:ContextMenu>
                    </md:FAB.ContextMenu>
                </md:FAB>
            </md:WrapLayout>

            <md:Label
                FontSize="18"
                HorizontalOptions="Start"
                Text="{Binding TestString, Mode=TwoWay}" />
        </VerticalStackLayout>
    </ScrollView>

Thanks

**Comment by yiszza** [comment]
Cannot reproduce in `net7.0-windows 10.0.19041.0` and `net8.0-windows 10.0.19041.0`, please provide your TargetFrameworks version.

**Comment by MahmoudAlEssawi** [comment]
Thanks for your reply. 

$(TargetFrameworks);net7.0-windows10.0.19041.0

**Comment by MahmoudAlEssawi** [comment]
I found that the bounds property of the context menu is (height:0, width:0)

**Comment by yiszza** [comment]
Sorry, maybe there's something wrong with the measure.
If I have time, I would try to fix it.

**Comment by MahmoudAlEssawi** [comment]
Take your time.
Thanks for your great effort.
