### ISSUE TITLE
NavigationBar in Shell

### ISSUE THREAD

**Issue by ziomek64** [yiszza/Material.Components.Maui#18]
Is it possible to just replace the navbar in shell with the one in mdc-maui? I have my TabBar like this now - 
```
    <TabBar Route="main">
        <Tab Title="Home" Icon="home.png">
            <ShellContent ContentTemplate="{DataTemplate Views:HomePage}" />
        </Tab>
        <Tab Title="Profile" Icon="user.png">
            <ShellContent ContentTemplate="{DataTemplate Views:ProfilePage}" />
        </Tab>
        <Tab Title="Anime" Icon="play_anime.png">
            <ShellContent ContentTemplate="{DataTemplate Views:AnimeListPage}" />
        </Tab>
        <Tab Title="Manga" Icon="read_manga.png">
            <ShellContent ContentTemplate="{DataTemplate Views:MangaListPage}" />
        </Tab>
        <Tab Title="Settings" Icon="settings.png">
            <ShellContent ContentTemplate="{DataTemplate Views:SettingsPage}" />
        </Tab>
    </TabBar>
```
So the tab bar is of route main and it contains 5 tabs/pages. I want to replace the look of it with the one in mdc-maui. I want to keep using shell. Btw, take a look here maybe https://github.com/dotnet/maui/issues/15441

**Comment by yiszza** [comment]
Thank you, but I don’t think this is possible.

**Comment by ziomek64** [comment]
> Thank you, but I don’t think this is possible.

Not possible now?

Do you think it would be to make it compatible with shell somehow in the future, with necessary changes?

**Comment by yiszza** [comment]
ShellItem does not handle layout, they only pass title and icon to the native view. We need the maui team to give us a more customizable shell view.

**Comment by ziomek64** [comment]
I guess we can close
