### ISSUE TITLE
Indicator is not redrawn when percent value is changed

### ISSUE THREAD

**Issue by OlegRakovich** [yiszza/Material.Components.Maui#21]
In my app, I am using ProgressIndicator to display the progress. The Percent property of ProgressIndicator is bound to a property of my ViewModel. Whenever value of that property is changed, ProgressIndicator still displays initial progress, even though I see in debugger that new value was accepted by Percent property and OnPercentChanged method was triggered.
As for now I can work-around that issue by triggering OnPropertyChanged manually which causes ProgressIndicator to display valid progress, but it looks like a bug to me - it should be triggered automatically.
Please take a look at the pull request #20 which proposes a fix to this issue.

**Comment by ziomek64** [comment]
Its normal to ensure by yourself that on property changed is triggered in whole maui

**Comment by OlegRakovich** [comment]
If you have a Label element on your page, whenever text of that label is changed, you are not required to trigger label's OnPropertyChanged method, as it re-draws automatically. This statement is true for most controls I've used so far. If this library is not following that design choice intentionally, then I'll keep using the workaround, but I think it's something that was simply missed, as OnPropertyChanged is automatically called for other properties in ProgressIndicator.

**Comment by ziomek64** [comment]
> If you have a Label element on your page, whenever text of that label is changed, you are not required to trigger label's OnPropertyChanged method, as it re-draws automatically. This statement is true for most controls I've used so far. If this library is not following that design choice intentionally, then I'll keep using the workaround, but I think it's something that was simply missed, as OnPropertyChanged is automatically called for other properties in ProgressIndicator.

No, it doesn't work like that for me, I need onpropertychanged on labels, image sources, even observablecollections (if replacing whole), lists, just about anything

**Comment by yiszza** [comment]
Thank you for your PR, it is indeed a bug, but I may not merge it right now. The current focus of work is #16 , where all the controls will be reimplemented. If you are interested, take a look [here](https://github.com/mdc-maui/mdc-maui/tree/develop).

**Comment by OlegRakovich** [comment]
Sounds good, I'll keep using the workaround for now. I'll close the PR and open a new one if new reimplemented version still has it.
