### ISSUE TITLE
Typing into a TextField does not have the text appear

### ISSUE THREAD

**Issue by asusralis** [yiszza/Material.Components.Maui#22]
When I type into the text field, the keyboard acts as there is text because the word suggestions change, but no text appears in the field. Setting the text in XAML works, clicking on suggestions in the android keyboard works, and backspace removes the text, but actual typing does not have any text appear.

**Comment by TimothyFran** [comment]
Have you managed to solve this? Having same problem

[Screen recording](https://filedn.com/l75coKMbsVGJXJ84utNi3Gj/2023-07-02-11-26-32.mp4)

**Comment by yiszza** [comment]
Fixed in 158da7b

**Comment by Humble2020** [comment]
same here. it does not appear in the textbox ...  and again can't we atleast be able to control the corner radius of the button?
i don't like to use the corner radius button on the project i am working on...
also "isPassword" is missing? when typing password it should be masked with dots
