### ISSUE TITLE
RTL horizontal alignment goes wrong on all components. 

### ISSUE THREAD

**Issue by MahmoudAlEssawi** [yiszza/Material.Components.Maui#23]
![Screenshot 2023-06-26 045228](https://github.com/mdc-maui/mdc-maui/assets/90508176/66b6e3b3-1539-4f9e-be0d-8a216bfed9fc)
![Screenshot 2023-06-26 045237](https://github.com/mdc-maui/mdc-maui/assets/90508176/91a72b6e-3617-4a3d-b80c-0acfa929249d)

I have to set extra white space to force text to appear.

more white space moves the text to the left

**Comment by yiszza** [comment]
Is this possibly due to the RTL font?

**Comment by MahmoudAlEssawi** [comment]
Can you explain more please?
