### ISSUE TITLE
Checkbox - Text

### ISSUE THREAD

**Issue by marcosgerene** [yiszza/Material.Components.Maui#25]
Hi,

I am receiving this error:

![image](https://github.com/mdc-maui/mdc-maui/assets/15945003/784eacba-1cf0-4541-bbb3-77c546088b70)

But on documentation the property exists.

https://mdc-maui.github.io/checkbox

My code:
![image](https://github.com/mdc-maui/mdc-maui/assets/15945003/3a300a19-0730-4a4a-81c0-c2f60a987d33)

![image](https://github.com/mdc-maui/mdc-maui/assets/15945003/294a338d-8406-4b4a-8592-7f7f118fc8af)

**Comment by yiszza** [comment]
The text property has been removed, but it seems that the document has not been updated in time, this is my fault.

**Comment by marcosgerene** [comment]
@yiszza No problem at all, I thought it was my fault because of Xamarin migration.

Can you gimme an example how to have the same layout as it was with the "Text" property.

```
<StackLayout Orientation="Horizontal">
    <material:CheckBox Text="My 1st chekbox-text" />
    <material:CheckBox Text="My 2nd chekbox-text" />
<StackLayout>
```

I guess it will be like:
```
<StackLayout Orientation="Horizontal">
    <StackLayout Orientation="Horizontal">
         <material:CheckBox />
         <Label Text="My 1st chekbox-text"  />
    </StackLayout>
    <StackLayout Orientation="Horizontal">
         <material:CheckBox />
         <Label Text="My 2nd chekbox-text"  />
    </StackLayout>
<StackLayout>
```

Is there any better way to have the same layout as it was meant to be?

**Comment by marcosgerene** [comment]
No problem
