### ISSUE TITLE
🤔 How can we set DynamicResource in style?

### ISSUE THREAD

**Issue by Strypper** [yiszza/Material.Components.Maui#28]
## Scope
I'm currently working on cleaning up my `XAML` code by moving all properties to the `Resources Group` for better organization and reusability. However, I'm encountering an issue as shown in the example below:
```xml
    <mdc:Card
        HeightRequest="170"
        Style="{x:DynamicResource FilledCardStyle}"
        WidthRequest="350"/>
```
I would like to achieve the following result, but when I tried using `BaseResourceKey` and `BasedOn`, it caused the app to crash. Is there a way to achieve this?
```xml
 <ContentView.Resources>
        <<Style
            x:Key="MaterialUICardStyle"
            BaseResourceKey="{x:DynamicResource FilledCardStyle}"
            TargetType="mdc:Card">
            <Setter Property="HeightRequest" Value="170" />
            <Setter Property="WidthRequest" Value="350" />
        </Style>
    </ContentView.Resources>

    <mdc:Card
        Style="{x:StaticResource MaterialUICardStyle}"/>
```

**Comment by yiszza** [comment]
BaseResourceKey is a string type.

Try: 
```xaml
<ContentView.Resources>
        <<Style
            x:Key="MaterialUICardStyle"
            BaseResourceKey="FilledCardStyle"
            TargetType="mdc:Card">
            <Setter Property="HeightRequest" Value="170" />
            <Setter Property="WidthRequest" Value="350" />
        </Style>
    </ContentView.Resources>

    <mdc:Card
        Style="{x:StaticResource MaterialUICardStyle}"/>
```

**Comment by Strypper** [comment]
> BaseResourceKey is a string type.
> 
> Try:
> 
> ```
> <ContentView.Resources>
>         <<Style
>             x:Key="MaterialUICardStyle"
>             BaseResourceKey="FilledCardStyle"
>             TargetType="mdc:Card">
>             <Setter Property="HeightRequest" Value="170" />
>             <Setter Property="WidthRequest" Value="350" />
>         </Style>
>     </ContentView.Resources>
> 
>     <mdc:Card
>         Style="{x:StaticResource MaterialUICardStyle}"/>
> ```

Thanks you this works!
