### ISSUE TITLE
Material You color theme compatibility

### ISSUE THREAD

**Issue by 1matin** [yiszza/Material.Components.Maui#36]
Hi, I am a user of your mdc-maui library and I really appreciate your work.
I have a question: does your library support color sync with mobile devices that use Material You design system? Material You is a new design system that adapts the color scheme of the app to the wallpaper of the device, or can be set manually. I think it would be great if your library could also sync the color of the web app with the mobile device. Is this feature planned or already implemented? If not, do you have any suggestions on how to achieve this? Thank you for your time and attention.

**Comment by albi005** [comment]
You could try using my library: https://github.com/albi005/MaterialColorUtilities

The package for .NET MAUI can generate color schemes from the wallpaper or an accent color.

**Comment by ziomek64** [comment]
@albi005 sounds great, it will work with this library?

**Comment by albi005** [comment]
Yes! This library already depends on and uses the colors from MaterialColorUtilities. The only difference is that MDC-MAUI adds a "Color" suffix at the end of color names, so you will have to:

1. Subclass MaterialColorService and override the Apply method:
```csharp

public class CustomMaterialColorService : MaterialColorService<CorePalette, Scheme<uint>, Scheme<Color>, LightSchemeMapper, DarkSchemeMapper>
{
    public CustomMaterialColorService(IOptions<MaterialColorOptions> options, IDynamicColorService dynamicColorService, IPreferences preferences) : base(options, dynamicColorService, preferences)
    {
    }

    protected override async void Apply()
    {
        foreach (KeyValuePair<string, Color> color in SchemeMaui.Enumerate())
        {
            _appResources[color.Key + "Color"] = color.Value;
        }
    }
}
```
2. Register the new service in `MauiProgram.cs` before `UseMauiApp<App>`:
```csharp
public static class MauiProgram
{
    public static MauiApp CreateMauiApp()
    {
        MauiAppBuilder builder = MauiApp
            .CreateBuilder()
            .UseMaterialColors<CustomMaterialColorService>()
            .UseMauiApp<App>();

		// ...

        return builder.Build();
    }
}
```

This will update the colors in the app's global `ResourceDictionary`, in turn updating any `{DynamicResource ColorName}` references, when dark mode is toggled, the source color or the color scheme change.

If you need any more help, feel free to ask.

**Comment by yiszza** [comment]
No plan, Material U dynamic themes only support android 12 and latest.
