### ISSUE TITLE
.net 8 version

### ISSUE THREAD

**Issue by ziomek64** [yiszza/Material.Components.Maui#37]
Hello,
When do you release .net 8 version or do we have to compile it ourselves? .net 8 released so it would be much appreciated.

**Comment by ziomek64** [comment]
I tried it myself with dev branch but maui can't find .UseMaterialComponents, so can't run it for some reason

**Comment by kannanrs** [comment]
please follow the sample with this release... it works...

**Comment by ziomek64** [comment]
> please follow the sample with this release... it works...

What release? I don't see anything. Send link

**Comment by kannanrs** [comment]
Hi.. its the develop repository download ... create a new project and reference the Material.Components.Maui project/dll...

follow the MainPage.xaml as in the sample.. it does build and run in .net8...

Regards

**Comment by sumowesley** [comment]
If it helps, I had the same issue as it didn't find the Material.Components.Maui.Extensions namespace. However, quitting VS 17.8 and restarting it did find the namespace.

**Comment by yiszza** [comment]
The dev branch has some breaking changes and their documentation is still waiting to be written.

**Comment by kannanrs** [comment]
Thank you @yiszza, waiting for the documentation update and new controls... Thank you for your time and efforts...

Regards

**Comment by kannanrs** [comment]
Hi...

The new samples project doesnt load for some reason...

Regards

**Comment by ziomek64** [comment]
> Hi...
> 
> The new samples project doesnt load for some reason...
> 
> Regards

What new samples dude?

**Comment by yiszza** [comment]
The new docs and sample project have been prepared.

**Comment by ziomek64** [comment]
@yiszza Thanks man, seems to be working for me in .net 8 now. I could finally upgrade my app

**Comment by kannanrs** [comment]
@yiszza ... Thank you for the great efforts... 


Regards and Wishes

**Comment by ziomek64** [comment]
> @yiszza ... Thank you for the great efforts...
> 
> Regards and Wishes

Why the dots man.......?
