### ISSUE TITLE
NavigationBarItems are not working properly after upgrading to 0.2.0 - preview

### ISSUE THREAD

**Issue by DharunAR** [yiszza/Material.Components.Maui#44]
My code before upgrading the package:

<mdc:NavigationBar x:Name="bar" BackgroundColor="White">
        <mdc:NavigationBarItem x:Name="home"
                               ActiveIndicatorColor="#ABB1D6"
                               IsActived="False"                              
                               BackgroundColour="Transparent" ActivedIconKind="Home" IconKind="Home" Text="Home" Clicked="HomeItem_Clicked">
         
        </mdc:NavigationBarItem>
        <mdc:NavigationBarItem x:Name="fav"
                               ActiveIndicatorColor="#ABB1D6"
                               BackgroundColour="Transparent"  ActivedIconKind="Star" IconKind="Star" Text="Favourites"   Clicked="FavItem_Clicked">
         
        </mdc:NavigationBarItem>
        <mdc:NavigationBarItem x:Name="menu"
                               ActiveIndicatorColor="Transparent"
                               BackgroundColour="Transparent"  ActivedIconKind="Menu" IconKind="Menu" Text="Menu" Clicked="MenuItem_Clicked">
        </mdc:NavigationBarItem>
    </mdc:NavigationBar>

Screenshot:
![image](https://github.com/mdc-maui/mdc-maui/assets/87979888/7d2949f9-a99e-4a76-a9c4-685aea26e4cb)

After upgrade, i did the following changes:

 <mdc:NavigationBar x:Name="bar" BackgroundColor="White">
     <mdc:NavigationBarItem x:Name="home" FontSize="40"
                            IsActived="False" ActiveIndicatorColor="#ABB1D6"                             
                            BackgroundColor="Transparent" IconData="{Static icon:Material.Home}" FontFamily="Roboto" Text="Home" Clicked="HomeItem_Clicked">
      
     </mdc:NavigationBarItem>
     <mdc:NavigationBarItem x:Name="fav" ActiveIndicatorColor="#ABB1D6"
                            BackgroundColor="Transparent" IconData="{Static icon:Material.Star}" Text="Favourites" Clicked="FavItem_Clicked">
      
     </mdc:NavigationBarItem>
     <mdc:NavigationBarItem x:Name="menu"
                            ActiveIndicatorColor="Transparent"
                            BackgroundColor="Transparent" IconData="{Static icon:Material.Menu}" FontSize="50" Text="Menu" Clicked="MenuItem_Clicked">

     </mdc:NavigationBarItem>
 </mdc:NavigationBar>

But the navigationbar not displaying properly, below is the screenshot:

![image](https://github.com/mdc-maui/mdc-maui/assets/87979888/2f6d62a2-73c4-45bc-bd25-09c5e15fe81a)

What am i missing here? Please give some inputs on fixing up this.

**Comment by DharunAR** [comment]
@yiszza  Can you help me out with this issue?

**Comment by yiszza** [comment]
Copy! Pls wait next release.

**Comment by yiszza** [comment]
Fixed in 9e6c143, new release in [here](https://www.nuget.org/packages/Material.Components.Maui/0.2.1-preview).
