### ISSUE TITLE
ContextMenu only shows with long click

### ISSUE THREAD

**Issue by BinaryAssault** [yiszza/Material.Components.Maui#47]
Tested on Android A10 (emulator), A14 (physical device) and Windows 10. 

When using a context menu, it only will display if you long click on the icon, single clicks should expand the menu or there should be a property that allows either behavior 
![contextMenu](https://github.com/mdc-maui/mdc-maui/assets/19739224/68a59a21-d921-4d47-9546-12f44f7d1eb2)

MDC MAUI v0.2.1-preview
.NET 8
``````
xmlns:icon="clr-namespace:IconPacks.IconKind;assembly=IconPacks.Material"
xmlns:mdc="clr-namespace:Material.Components.Maui;assembly=Material.Components.Maui"
``````

``````
<mdc:IconButton
    BackgroundColor="Transparent"
    HorizontalOptions="Center"
    IconData="{Static icon:Material.MoreVert}"
    VerticalOptions="Center">
    <mdc:IconButton.ContextMenu>
        <mdc:ContextMenu>
            <mdc:MenuItem IconData="{Static icon:Material.Delete}" Text="Delete" />
            <mdc:MenuItem IconData="{Static icon:Material.Edit}" Text="Edit" />
            <mdc:MenuItem IconData="{Static icon:Material.ContentCopy}" Text="Copy" />
        </mdc:ContextMenu>
    </mdc:IconButton.ContextMenu>
</mdc:IconButton>
``````

**Comment by BinaryAssault** [comment]
This is still an issue with 0.2.2

**Comment by yiszza** [comment]
https://stackoverflow.com/questions/1942600/how-to-call-context-menu/2926081#2926081

**Comment by yiszza** [comment]
This is not a mistake. If you want to click to open the context menu, you can do this:
```c#
view?.ContextMenu?.Show(view, e.Touches[0]);
```
