### ISSUE TITLE
Support for ICommand.CanExecute

### ISSUE THREAD

**Issue by JWillisNetDev** [yiszza/Material.Components.Maui#49]
Binding commands to the `Command` property of buttons should respect the `ICommand.CanExecute(object?)` method to determine if the command is executable, and use a different styling when `CanExecute` returns false.

Currently, buttons will still invoke the ICommand's behavior even if CanExecute returns false and does not use a different style.

**Comment by Ruffythemonkey** [comment]
use the CommunityToolkit & CommunityToolkit.Maui

**Comment by JWillisNetDev** [comment]
This library itself needs to be updated in order to use ICommand interface properly or a decision should be made that it won't be supported in the future.

An example of this is this implementation: https://github.com/mdc-maui/mdc-maui/blob/34c507d795f451150d6a778eb46b2443b5345539/src/Material.Components.Maui/Components/Button/Button.cs#L123C21-L123C21

This could be changed to `if (Command?.CanExecute(CommandParameter)) { Command.Execute(CommandParameter); }`. 

Additionally, style triggers would have to be included to resemble the disabled styling if CanExecute returns a non-truthy value. I may work on it myself, but lots of libraries are dropping support for the Command pattern (MUDBlazor recently totally removed ICommand support) so I'm not sure if it fits the long-term goals of the project or not.

**Comment by yiszza** [comment]
Update: 6e97cdaf8cd53ee19b4125d968c5f3fbb88bf739
