### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Shahid-khan5** [yiszza/Material.Components.Maui#51]
Hi,
Thank you for the great library. I am planning to create my own library for .NET MAUI. Can I use this library as a base library? I am going to create .NET MAUI version of this [WPF Library](https://github.com/ghost1372/HandyControls)

**Comment by ziomek64** [comment]
It's MIT license, you can do whatever you want

**Comment by Shahid-khan5** [comment]
Thank you
