### ISSUE TITLE
Controls don't respect FontFamily property

### ISSUE THREAD

**Issue by Reimnop** [yiszza/Material.Components.Maui#63]
Hello, this package is great! However, I've noticed that the mdc controls do not respect the FontFamily property, which affects the look of my app.

# Reproduction
- Add a material control (e.g. `mdc:Button`)
- Add FontFamily property to it
- See that the font does not change

# Expected behavior
- The font changes according to the `FontFamily` property

# Code
```xaml
<VerticalStackLayout 
    Spacing="12" 
    VerticalOptions="Center">

    <!-- mdc button (doesn't work as expected) -->
    <mdc:Button 
        WidthRequest="256" 
        Text="Click me!" 
        FontFamily="RobotoRegular" />

    <!-- maui button (works) -->
    <Button 
        WidthRequest="256" 
        Text="Click me!" 
        FontFamily="RobotoRegular" />
</VerticalStackLayout>
```

# Image
![image](https://github.com/mdc-maui/mdc-maui/assets/56994757/d5c52ab8-2dcf-466d-8b2e-b58d8588109e)

**Comment by yiszza** [comment]
Maui's bug. https://github.com/dotnet/maui/issues/9252
